# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: nzdpa
email: david@anso.net.nz
description: > # this means to ignore newlines until "baseurl:"
  A space for my geeky experiments, failures and random ramblings.
  All views are my own and do not reflect those of my employer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.daveland.co.nz" # the base hostname & protocol for your site
twitter_username: davidanso
github_username:  nzdpa
linkedin_username:  david-anso-a85a69b

# Build settings
markdown: kramdown
